# Generated by Django 3.1.3 on 2020-11-05 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0002_auto_20201105_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juice',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='juice',
            name='percent',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stolean',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stolean',
            name='percent',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='water',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='water',
            name='percent',
            field=models.FloatField(),
        ),
    ]
